### PR TITLE
Fix JSX in README

### PR DESCRIPTION
**Pull request by stephenmathieson**

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Thanks!

**Comment by stephenmathieson** [comment]
For sure. Hope all is well with you! I miss working with you 😄

**Comment by vadimdemedes** [comment]
Thanks, Stephen, likewise! Indeed, we were an A-team! I'm still in the #ipo-team channel btw :D

**Comment by stephenmathieson** [comment]
Haha no way! It's awesome that you're still there.

Are you using this library at work now? Or just messing around because Apollo is gigantic? Either way, this is a super cool idea. I'll be testing it out in a few days on a little side thing I've been hacking on.

**Comment by vadimdemedes** [comment]
Honestly, I've had an idea for a GQL client for a very long time, I had a cool name and I just wanted to make it no matter what :) Not using at work, but maybe I'll test drive it in some low-traffic pages. Awesome, let me know how it works out!

**Pull request merged**
