### PR TITLE
Use Prettier to format usage section

### PR DESCRIPTION
**Pull request by frinyvonnick**
Hi,

Thank you for your work 👍 

I used Prettier to format the code in the usage section. I find it more readable. What do you think of it ?

### CODE REVIEW

**Comment by ducan-ne** [comment]
draqula already applied prettier

https://github.com/vadimdemedes/draqula/blob/633e9322e902bd6ffe7addd1dec661f263e6cc32/package.json#L78-L84

**Comment by frinyvonnick** [comment]
My bad I didn't saw this configuration for Prettier. I applied the rules by default. My original issue was regarding the indentation that can be configure in IDEs so it displays nicely for everyone. The documentation is most of the time read in a browser (is it really true?) in which you can't configure indentation size. The tabulation are too much in the README in my humble opinion.

**Comment by damassi** [comment]
I was just going to post about this: 

Screen Shot 2019-09-09 at 9 33 10 AM

This is hard to read and looks kinda sloppy for new arrivals to the library. (The actual docs from the docs site looks good however.)

**Comment by sindresorhus** [comment]
Use https://github.com/sindresorhus/tab-size-on-github or https://github.com/sindresorhus/refined-github to fix the tab size. You should also complain to support@github.com about fixing the default tab size.

**Comment by damassi** [comment]
Given that the docs look nicely formatted, it's a bit of a stretch to ask that a user install a browser plugin to read the README in a sane way. The tabs vs spaces argument shouldn't get in the way of user experience.

**Comment by frinyvonnick** [comment]
I didn't want to create an argument in here. I agree with both of you. I browsed a few repositories from @vadimdemedes and all README are like this one. It seems to be a choice. 

Thank you for your answers. Didn't know about [https://github.com/sindresorhus/tab-size-on-github](https://github.com/sindresorhus/tab-size-on-github) thank you @sindresorhus 👍

I close this PR 😄

**Pull request closed without merging**
